guitar_feeling_homepage:
    path:     /
    defaults: { _controller: GuitarFeelingBundle:Homepage:index }

guitar_feeling_tutorials:
    path:     /tutorials/
    defaults: { _controller: GuitarFeelingBundle:Tutorial:index }

guitar_feeling_tutorials_show:
    path:     /tutorials/{id}
    defaults: { _controller: GuitarFeelingBundle:Tutorial:show }
    methods: [GET]
    requirements:
      id: \d+

guitar_feeling_tutorials_new:
    path:     /tutorials/new
    defaults: { _controller: GuitarFeelingBundle:Tutorial:new }

guitar_feeling_tutorials_create:
    path:     /tutorials/create
    methods: [POST]
    defaults: { _controller: GuitarFeelingBundle:Tutorial:create }
