guitar_feeling_homepage:
    path:     /
    defaults: { _controller: GuitarFeelingBundle:Homepage:index }

guitar_feeling_tutorials:
    path:     /tutorials/
    defaults: { _controller: GuitarFeelingBundle:Tutorial:index }
    methods: [GET]

guitar_feeling_tutorials_show:
    path:     /tutorials/{id}
    defaults: { _controller: GuitarFeelingBundle:Tutorial:show }
    methods: [GET]
    requirements:
      id: \d+

guitar_feeling_tutorials_new:
    path:     /tutorials/new
    defaults: { _controller: GuitarFeelingBundle:Tutorial:new }
    methods: [GET]

guitar_feeling_tutorials_create:
    path:     /tutorials/create
    defaults: { _controller: GuitarFeelingBundle:Tutorial:create }
    methods: [POST]

guitar_feeling_tutorials_edit:
    path:     /tutorials/{id}/edit
    defaults: { _controller: GuitarFeelingBundle:Tutorial:edit }
    methods: [GET]

guitar_feeling_tutorials_publish:
    path:     /tutorials/{id}/publish
    defaults: { _controller: GuitarFeelingBundle:Tutorial:publish }
    methods: [POST]

guitar_feeling_tutorials_update:
    path:     /tutorials/{id}
    defaults: { _controller: GuitarFeelingBundle:Tutorial:update }
    methods: [POST]
    requirements:
      id: \d+

guitar_feeling_tutorials_delete:
    path:     /tutorials/{id}/delete
    defaults: { _controller: GuitarFeelingBundle:Tutorial:delete }
    methods: [DELETE]
