guitar_feeling:
    resource: "@GuitarFeelingBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
