<?php

namespace GuitarFeelingBundle\Repository;

/**
 * TutorialLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorialLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
